// Generated by CoffeeScript 1.6.3
(function() {
  var CallApi, LogOn, SetURL, fogbugzURL, https, xml2js;

  https = require('https');

  xml2js = require('xml2js');

  fogbugzURL = 'https://claudiowilson.fogbugz.com/api.asp?';

  LogOn = function(username, password, token, callback) {
    return CallApi('cmd=logon&email=' + username + '&password=' + password, null, function(err, result) {
      if (err) {
        return callback(new Error('Error logging in ' + err.message));
      } else {
        return callback(null, result['token'][0]);
      }
    });
  };

  SetURL = function(url) {
    return fogbugzURL = url;
  };

  CallApi = function(commandText, token, callback) {
    var xml;
    if (token == null) {
      token = '';
    }
    if (!fogbugzURL) {
      callback(new Error('You have not specified a URL to call the API with'));
      return;
    }
    xml = '';
    return https.get(fogbugzURL + commandText + token, function(response) {
      response.on('data', function(chunk) {
        return xml += chunk;
      });
      response.on('error', function(error) {
        return callback(new Error(error.message));
      });
      return response.on('end', function() {
        return xml2js.parseString(xml, function(err, result) {
          if (result['response']['error']) {
            return callback(new Error(JSON.stringify(result['response']['error'])));
          } else {
            return callback(null, result['response']);
          }
        });
      });
    });
  };


}).call(this);
