// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, fogbugz, settings;

  express = require('express');

  fogbugz = require('./../fogbugz');

  settings = require('./settings');

  app = express();

  app.configure(function() {
    app.use(express.logger('dev'));
    return app.use(express.bodyParser());
  });

  app.get('/', function(request, response) {
    return fogbugz.LogOn(settings.fogbugzUser, settings.fogbugzPassword, null, function(error, token) {
      return console.log(token);
    });
  });

  app.listen(3000);

  console.log('Listening on port 3000....');

}).call(this);
