// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, fogbugz, settings;

  express = require('express');

  fogbugz = require('./../fogbugz');

  settings = require('./settings');

  app = express();

  app.configure(function() {
    app.use(express.logger('dev'));
    return app.use(express.bodyParser());
  });

  fogbugz.SetURL(settings.fogbugzURL);

  app.get('/', function(request, response) {
    return fogbugz.LogOn(settings.fogbugzUser, settings.fogbugzPassword, function(error, token) {
      return fogbugz.ListProjects({
        'fWrite': true,
        'ixProject': 1,
        'fIncludeDeleted': 1
      }, token, function(err, result) {
        if (err) {
          return console.log(err.message);
        } else {
          return console.log(result);
        }
      });
    });
  });

  app.listen(3000);

  console.log('Listening on port 3000....');

}).call(this);
